---
executor:
    # Default executor
    plugin: k8s-vm
    k8s:
      options:
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: kubernetes.default
            resources:
                cpu:
                    # Number of cpu cores
                    micro: "0.5"
                    low: 2
                    high: 6
                    turbo: 12
                memory:
                    # Memory in GB
                    micro: 1
                    low: 2
                    high: 12
                    turbo: 16
            # Default build timeout for all builds in this cluster
            buildTimeout: 90
            # Default max build timeout
            maxBuildTimeout: 120
            # k8s node selectors for approprate pod scheduling
            nodeSelectors: {}
            preferredNodeSelectors: {}
            annotations: {}
        # Launcher image to use
        launchImage: screwdrivercd/launcher
        # Container tags to use
        launchVersion: stable
        # Circuit breaker config
        fusebox:
            breaker:
                # in milliseconds
                timeout: 10000
    k8s-vm:
      options:
        # Configuration of Docker
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: kubernetes.default
            # Resources for build pod
            resources:
                cpu:
                    # Number of cpu cores
                    micro: 1
                    low: 2
                    high: 6
                    turbo: 12
                memory:
                    # Memory in GB
                    micro: 1
                    low: 2
                    high: 12
                    turbo: 16
            # Default build timeout for all builds in this cluster
            buildTimeout: 90
            # Default max build timeout
            maxBuildTimeout: 120
            # k8s node selectors for approprate pod scheduling
            nodeSelectors: {}
            preferredNodeSelectors: {}
        # Launcher image to use
        launchImage: screwdrivercd/launcher
        # Launcher container tag to use
        launchVersion: stable
        # Circuit breaker config
        fusebox:
            breaker:
                # in milliseconds
                timeout: 10000
#     jenkins:
#       options:
#         # Configuration of Jenkins
#         jenkins:
#             host: jenkins.default
#             port: 8080
#             username: screwdriver
#             password: "WOW-AN-EVEN-MORE-INSECURE-PASSWORD!!!!"
#             # Default build timeout (in minutes)
#             buildTimeout: 90
#             # Default max build timeout (in minutes)
#             maxBuildTimeout: 120

ecosystem:
    # Externally routable URL for the User Interface
    api: https://api.screwdriver.cd
    # Externally routable URL for the Artifact Store
    store: https://store.screwdriver.cd

redis:
    # Host of redis cluster
    host: 127.0.0.1
    # Password to connect to redis cluster
    # password: null
    # Port of redis cluster
    port: 6379
    # Prefix for the queue name
    # prefix: 'beta-'
    # Flag to enable client for TLS-based communication
    tls: false
plugins:
    blockedBy:
      # re-enqueue in 1 mins if blocked
      reenqueueWaitTime: 1
      # job is blocking for maximum 120 mins = build timeout
      blockTimeout: 120
      # job blocked by itself
      blockedBySelf: true
